#!/usr/bin/env bash
set -euo pipefail

# x-generate.sh
# - Single source generator based on ./conf.yml
# - Outputs:
#   * ./dnsmasq.d/dns-hosts with a single line mapping all hosts -> NGINX container IP
#   * ./conf-nginx/*.conf per host using ./nginx.tmpl.conf and its backend ip from conf.yml
#
# YAML expectations (minimal subset):
# Preferred schema:
# targets:
#   - host: a.example.com
#     ips:
#       - 1.2.3.4   # first entry is used
#
# Notes:
# - Backend connections are https://<ip> in the generated NGINX confs.
# - NGINX container IP defaults to 172.30.0.3.

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT_DIR"

CONF_YML="${ROOT_DIR}/conf.yml"
NGINX_TEMPLATE="${ROOT_DIR}/nginx.tmpl.conf"
NGINX_OUT_DIR="${ROOT_DIR}/conf-nginx"
DNS_HOSTS_FILE="${ROOT_DIR}/dnsmasq.d/dns-hosts"

if [[ ! -f "$CONF_YML" ]]; then
  echo "[x-gen] ERROR: conf.yml not found at $CONF_YML" >&2
  exit 1
fi
if [[ ! -f "$NGINX_TEMPLATE" ]]; then
  echo "[x-gen] ERROR: nginx template not found at $NGINX_TEMPLATE" >&2
  exit 1
fi

# NGINX container IP static default to keep script portable.
NGINX_IP="172.31.200.3"

# Extract "<ip>|<host>|<upstream>|<header_key>:<header_val>,..." tuples from conf.yml
read_pairs() {
  awk '
    function emit() {
      if (host != "" && ip != "") {
        oh = (up != "" ? up : host);
        # Remove pipe characters from host/upstream if any (sanity check)
        gsub(/\|/, "", host);
        gsub(/\|/, "", oh);
        print ip "|" host "|" oh "|" headers
      }
      host=""; ip=""; up=""; in_ips=0; headers=""; in_headers=0;
    }
    BEGIN { host=""; ip=""; up=""; in_ips=0; headers=""; in_headers=0; }
    /^[[:space:]]*#/ { next }
    /^[[:space:]]*$/ { next }

    # Start of a new target list item
    /^[[:space:]]*-[[:space:]]host:/ {
      emit();
      line=$0; sub(/#.*/,"",line); split(line,a,":"); host=a[2]; gsub(/^[[:space:]]+|[[:space:]]+$/,"",host);
      next
    }
    # host field without list marker
    /^[[:space:]]*host:[[:space:]]*/ {
      emit();
      line=$0; sub(/#.*/,"",line); split(line,a,":"); host=a[2]; gsub(/^[[:space:]]+|[[:space:]]+$/,"",host);
      next
    }
    # upstream_host field
    /^[[:space:]]*-?[[:space:]]*upstream_host:[[:space:]]*/ {
      line=$0; sub(/#.*/,"",line); split(line,a,":"); u=a[2]; gsub(/^[[:space:]]+|[[:space:]]+$/,"",u);
      up=u; next
    }
    # ips field
    /ips:[[:space:]]*$/ { in_ips=1; in_headers=0; next }
    # first IP list entry
    in_ips && /^[[:space:]]*-[[:space:]]*/ {
      val=$0; sub(/^[[:space:]]*-[[:space:]]*/,"",val); gsub(/^[[:space:]]+|[[:space:]]+$/,"",val);
      if (ip == "") ip=val;
      next
    }
    # override_headers field
    /override_headers:[[:space:]]*$/ { in_headers=1; in_ips=0; next }
    # header entry: - key: value
    in_headers && /^[[:space:]]*-[[:space:]]*/ {
      line=$0; sub(/^[[:space:]]*-[[:space:]]*/,"",line);
      p=index(line, ":");
      if (p > 0) {
        key=substr(line, 1, p-1); gsub(/^[[:space:]]+|[[:space:]]+$/,"",key);
        val=substr(line, p+1); gsub(/^[[:space:]]+|[[:space:]]+$/,"",val);
        if (key != "" && val != "") {
          if (headers != "") headers = headers ","
          headers = headers key ":" val
        }
      }
      next
    }
    END { emit(); }
  ' "$CONF_YML" | sed '/^[[:space:]]*$/d'
}

PAIRS=()
if command -v mapfile >/dev/null 2>&1; then
  mapfile -t PAIRS < <(read_pairs)
else
  while IFS= read -r __line; do
    [[ -n "$__line" ]] && PAIRS+=("$__line")
  done < <(read_pairs)
fi

if [[ ${#PAIRS[@]} -eq 0 ]]; then
  echo "[x-gen] ERROR: No targets parsed from conf.yml. Check the file format." >&2
  exit 1
fi

# 1) Generate header overrides mapping file
# We'll use a local associative array to group headers by their normalized key
# (e.g. "authorization", "user-agent")
HEADERS_FILE="${NGINX_OUT_DIR}/00-proxy-headers.local.conf"
HEADERS_INC_FILE="${NGINX_OUT_DIR}/00-proxy-headers-location.inc"
{
  echo "# 00-proxy-headers.local.conf"
  echo "# Auto-generated by x-generate.sh based on override_headers in conf.yml"
  echo "# Do not edit this file manually."
  echo

  # Extract all unique header keys (lowercase)
  # shellcheck disable=SC2001
  ALL_KEYS=$(printf "%s\n" "${PAIRS[@]}" | cut -d'|' -f4 | tr ',' '\n' | cut -d':' -f1 | tr '[:upper:]' '[:lower:]' | sort -u | sed '/^$/d')

  # Clear the include file first
  : > "$HEADERS_INC_FILE"

  for key in $ALL_KEYS; do
    # NGINX variable name based on header key (replace - with _)
    var_name="sb_${key//-/_}"
    # Incoming header variable (replace - with _)
    incoming_var="http_${key//-/_}"

    echo "map \$host \$${var_name} {"
    echo "    default \$$incoming_var;"
      
    for p in "${PAIRS[@]}"; do
      IFS='|' read -r ip host upstream headers <<< "$p"
      # Find the specific header in the headers list for this host
      # We use a simple loop over the comma-separated headers
      IFS=',' read -ra HDR_ARR <<< "$headers"
      for h in "${HDR_ARR[@]}"; do
        h_key=$(echo "$h" | cut -d':' -f1 | tr '[:upper:]' '[:lower:]')
        h_val=$(echo "$h" | cut -d':' -f2-)
        if [[ "$h_key" == "$key" ]]; then
          echo "    $host \"$h_val\";"
        fi
      done
    done
    echo "}"
    echo

    # Add the proxy_set_header to the include file
    # Use capitalized version for header name
    cap_key=$(echo "$key" | awk '{for(i=1;i<=NF;i++){$i=toupper(substr($i,1,1)) substr($i,2)}}1' FS=- OFS=-)
    echo "proxy_set_header $cap_key \$$var_name;" >> "$HEADERS_INC_FILE"
  done
} > "$HEADERS_FILE"
echo "[x-gen] Wrote ${HEADERS_FILE} and ${HEADERS_INC_FILE} with header overrides"

# 2) Build a sorted unique host list for dns-hosts
TMP_HOSTS=$(mktemp)
trap 'rm -f "$TMP_HOSTS"' EXIT
for p in "${PAIRS[@]}"; do
  IFS='|' read -r ip host upstream headers <<< "$p"
  printf "%s\n" "$host" >> "$TMP_HOSTS"
done
# shellcheck disable=SC2002
ALL_HOSTS=( $(cat "$TMP_HOSTS" | sort -u) )

# 1) Write dns-hosts with a single line
mkdir -p "$(dirname "$DNS_HOSTS_FILE")"
{
  echo "# dns-hosts"
  echo "# Auto-generated by x-generate-from-conf.sh from conf.yml"
  echo "# All hosts map to the internal NGINX IP; NGINX proxies to real backends."
  echo "# Example: $NGINX_IP foo.example.com bar.example.com"
  echo
  printf "%s" "$NGINX_IP"
  for h in "${ALL_HOSTS[@]}"; do
    printf " %s" "$h"
  done
  printf "\n"
} > "$DNS_HOSTS_FILE"
echo "[x-gen] Wrote ${DNS_HOSTS_FILE} with ${#ALL_HOSTS[@]} hostnames -> ${NGINX_IP}"

# 2) Generate dnsmasq configuration to block IPv6 for these hosts
DNSMASQ_CONF="${ROOT_DIR}/dnsmasq.d/shadybridge.conf"
{
  echo "# dnsmasq configuration to block IPv6 for intercepted hosts"
  echo "# Auto-generated by x-generate.sh"
  for h in "${ALL_HOSTS[@]}"; do
    echo "address=/${h}/$NGINX_IP"
  done
} > "$DNSMASQ_CONF"
echo "[x-gen] Wrote ${DNSMASQ_CONF} to block IPv6 for ${#ALL_HOSTS[@]} hostnames"

# 3) Generate per-host NGINX configs (last pair wins by overwriting)
mkdir -p "$NGINX_OUT_DIR"
# Preserve pinned/manual configs like 00-*.conf (e.g., 00-tuning.conf) by excluding them from deletion
find "$NGINX_OUT_DIR" -type f -name "*.conf" ! -name "00-*" -delete 2>/dev/null || true

for p in "${PAIRS[@]}"; do
  IFS='|' read -r ip host upstream headers <<< "$p"
  out="${NGINX_OUT_DIR}/${host//[^A-Za-z0-9._-]/_}.conf"
  sed -e "s#__SERVER_NAME__#${host//\/\\}#g" \
      -e "s#__BACKEND_IP__#${ip//\/\\}#g" \
      -e "s#__UPSTREAM_HOST__#${upstream//\/\\}#g" \
      "$NGINX_TEMPLATE" > "$out"
  echo "[x-gen] NGINX: $host -> https://$ip (SNI: $upstream) (${out})"
done

count=$(ls -1 "$NGINX_OUT_DIR"/*.conf 2>/dev/null | wc -l | tr -d ' ')
echo "[x-gen] Generated $count NGINX server configs in $NGINX_OUT_DIR"

echo "[x-build] Generating/validating certificates..."
"${ROOT_DIR}/x-generate-certs.sh"
