#!/usr/bin/env bash
set -euo pipefail

# x-generate.sh
# - Single source generator based on ./conf.yml
# - Outputs:
#   * ./dnsmasq.d/dns-hosts with a single line mapping all hosts -> NGINX container IP
#   * ./conf-nginx/*.conf per host using ./nginx.tmpl.conf and its backend ip from conf.yml
#
# YAML expectations (minimal subset):
# Preferred schema:
# targets:
#   - host: a.example.com
#     ips:
#       - 1.2.3.4   # first entry is used
#
# Notes:
# - Backend connections are https://<ip> in the generated NGINX confs.
# - NGINX container IP defaults to 172.30.0.3.

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT_DIR"

CONF_YML="${ROOT_DIR}/conf.yml"
NGINX_TEMPLATE="${ROOT_DIR}/nginx.tmpl.conf"
NGINX_OUT_DIR="${ROOT_DIR}/conf-nginx"
DNS_HOSTS_FILE="${ROOT_DIR}/dnsmasq.d/dns-hosts"

if [[ ! -f "$CONF_YML" ]]; then
  echo "[x-gen] ERROR: conf.yml not found at $CONF_YML" >&2
  exit 1
fi
if [[ ! -f "$NGINX_TEMPLATE" ]]; then
  echo "[x-gen] ERROR: nginx template not found at $NGINX_TEMPLATE" >&2
  exit 1
fi

# NGINX container IP static default to keep script portable.
NGINX_IP="172.30.0.3"

# Extract "<ip>|<host>" pairs from conf.yml (new schema only)
read_pairs() {
  awk '
    BEGIN { host=""; ip=""; in_ips=0 }
    /^[[:space:]]*#/ { next }
    /^[[:space:]]*$/ { next }

    # Schema: host: <name>
    /host:[[:space:]]*/ {
      line=$0; sub(/#.*/,"",line); split(line,a,":"); host=a[2]; gsub(/^[[:space:]]+|[[:space:]]+$/,"",host);
      in_ips=0; ip=""; next
    }
    # Schema: ips:
    /ips:[[:space:]]*$/ { in_ips=1; next }
    # First list entry is used for backend mapping
    in_ips && /^[[:space:]]*-[[:space:]]*/ {
      val=$0; sub(/^[[:space:]]*-[[:space:]]*/,"",val); gsub(/^[[:space:]]+|[[:space:]]+$/,"",val);
      if (ip=="" && host!="") { ip=val; if (ip!="") { print ip "|" host } }
      next
    }
  ' "$CONF_YML" | sed '/^[[:space:]]*$/d'
}

PAIRS=()
if command -v mapfile >/dev/null 2>&1; then
  mapfile -t PAIRS < <(read_pairs)
else
  while IFS= read -r __line; do
    [[ -n "$__line" ]] && PAIRS+=("$__line")
  done < <(read_pairs)
fi

if [[ ${#PAIRS[@]} -eq 0 ]]; then
  echo "[x-gen] ERROR: No targets parsed from conf.yml. Check the file format." >&2
  exit 1
fi

# Build a sorted unique host list for dns-hosts
TMP_HOSTS=$(mktemp)
trap 'rm -f "$TMP_HOSTS"' EXIT
for p in "${PAIRS[@]}"; do
  printf "%s\n" "${p#*|}" >> "$TMP_HOSTS"
done
# shellcheck disable=SC2002
ALL_HOSTS=( $(cat "$TMP_HOSTS" | sort -u) )

# 1) Write dns-hosts with a single line
mkdir -p "$(dirname "$DNS_HOSTS_FILE")"
{
  echo "# dns-hosts"
  echo "# Auto-generated by x-generate-from-conf.sh from conf.yml"
  echo "# All hosts map to the internal NGINX IP; NGINX proxies to real backends."
  echo "# Example: $NGINX_IP foo.example.com bar.example.com"
  echo
  printf "%s" "$NGINX_IP"
  for h in "${ALL_HOSTS[@]}"; do
    printf " %s" "$h"
  done
  printf "\n"
} > "$DNS_HOSTS_FILE"
echo "[x-gen] Wrote ${DNS_HOSTS_FILE} with ${#ALL_HOSTS[@]} hostnames -> ${NGINX_IP}"

# 2) Generate per-host NGINX configs (last pair wins by overwriting)
mkdir -p "$NGINX_OUT_DIR"
find "$NGINX_OUT_DIR" -type f -name "*.conf" -delete 2>/dev/null || true

for p in "${PAIRS[@]}"; do
  ip="${p%%|*}"; host="${p#*|}"
  out="${NGINX_OUT_DIR}/${host//[^A-Za-z0-9._-]/_}.conf"
  sed -e "s#__SERVER_NAME__#${host//\/\\}#g" \
      -e "s#__BACKEND_IP__#${ip//\/\\}#g" \
      "$NGINX_TEMPLATE" > "$out"
  echo "[x-gen] NGINX: $host -> https://$ip (${out})"
done

count=$(ls -1 "$NGINX_OUT_DIR"/*.conf 2>/dev/null | wc -l | tr -d ' ')
echo "[x-gen] Generated $count NGINX server configs in $NGINX_OUT_DIR"

echo "[x-build] Generating/validating certificates..."
"${ROOT_DIR}/x-generate-certs.sh"
